package persistence;

import datarecords.CustomerData;
import persistence.database.DBProvider;

import javax.sql.DataSource;
import java.sql.*;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * This class knows everything about storing and retrieving customers from
 * the database. At the moment only returns dummy object with an id that is set.
 * Normally it will connect to a database and do all the handling.
 *
 * @author Informatics Fontys Venlo
 */
class CustomerStorageServiceImpl implements CustomerStorageService {
    private final DataSource dataSource;
    public CustomerStorageServiceImpl(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    public CustomerStorageServiceImpl(){
        this.dataSource = DBProvider.getDataSource("jdbc.pg.prod");
    }

    @Override
    public CustomerData add(CustomerData customerData) {
        // Create dummy customerData object with id. Normally, the id would be generated by the database
        return new CustomerData(customerData.id(), customerData.firstName(), customerData.lastName(),
                customerData.dob(), customerData.email());
    }

    public CustomerData getCustomer(String customer_Id){
        DataSource db = DBProvider.getDataSource("jdbc.pg.prod");
        String query = "SELECT * FROM booking_data WHERE id = ?";
        CustomerData customer = null;

        try (Connection con = db.getConnection(); PreparedStatement pstm = con.prepareStatement(query)) {
            pstm.setString(1,customer_Id);
            ResultSet result = pstm.executeQuery();
            System.out.println("JUST RECEIVED: ");
            String id = "";
            String fName = "";
            String lName = "";
            LocalDate lDate = null;
            String mail = "";
            while (result.next()) {
                id = result.getString("id");
                fName = result.getString("emp_Id");
                lName = result.getString("flight_Id");
                Date dobSQL = result.getDate("booking_Date");
                mail = result.getString("email");
                lDate = dobSQL.toLocalDate();
                System.out.println("Customer with id: " + id + ", " + fName + ",id: " + lName + ", " + lDate + ", " + mail);
            }
            customer = new CustomerData(id, fName, lName, lDate, mail);

        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(customer != null){
            return customer;
        }
        return null;
    }
}
